[features]
seeds = false
skip-lint = false
[programs.localnet]
dice = "HdRPNnu76KmU4NzY1XvHrhvyGyasPCvsaZ2ogzhWxwGL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marche/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
